### ISSUE TITLE
Crash on Android 6+

### ISSUE THREAD

**Issue by Pugnator** [Pugnator/HAMTESTRUS#7]
06-22 20:36:27.484 3208-3208/com.nonamegarage.hamtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.nonamegarage.hamtest, PID: 3208
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nonamegarage.hamtest/com.nonamegarage.hamtest.QuestionActivity}: java.lang.NegativeArraySizeException: -1
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.NegativeArraySizeException: -1
                                                                            at com.nonamegarage.hamtest.QuestionActivity.resetTestState(QuestionActivity.java:251)
                                                                            at com.nonamegarage.hamtest.QuestionActivity.onCreate(QuestionActivity.java:181)
                                                                            at android.app.Activity.performCreate(Activity.java:6237)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Pugnator** [comment]
the problem is for new installs only
